version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    container_name: django_db
    user: postgres
    restart: always
    environment:
      - POSTGRES_DB=djangoecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - type: 'bind'
        source: './volumes/dbdata'
        target: '/var/lib/postgresql/data'

  redis:
    image: 'redis:7.0.9-alpine'
    ports:
      - 6379:6379
    volumes:
      - type: 'bind'
        source: './volumes/redisdata'
        target: '/data'